version: "3.8"

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web
            - daphne
            - frontend
        volumes:
            - media_volume:/usr/src/djangobnb_backend/media
            - static_volume:/usr/src/djangobnb_backend/static
            - /var/www/certbot:/var/www/certbot
            - /var/certbot/conf:/etc/letsencrypt
            - /webapps/Djangobnb_backend/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network
        restart: unless-stopped

    web:
        build: ./djangobnb_backend
        command: gunicorn djangobnb_backend.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./djangobnb_backend/:/usr/src/djangobnb_backend/
            - media_volume:/usr/src/djangobnb_backend/media
            - static_volume:/usr/src/djangobnb_backend/static
        expose:
            - "8000"
        env_file:
            - ./.env
        depends_on:
            - db
        networks:
            - app-network

    daphne:
        build: ./djangobnb_backend
        command: daphne --bind 0.0.0.0 -p 8002 djangobnb_backend.asgi:application
        expose:
            - "8002"
        env_file:
            - ./.env
        depends_on:
            - db
        networks:
            - app-network

    frontend:
        build: ../Djangobnb_frontend
        expose:
            - "3000"
        networks:
            - app-network

    db:
        image: postgres:15
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgresuser
            - POSTGRES_PASSWORD=postgrespassword
            - POSTGRES_DB=djangobnb
        networks:
            - app-network

    certbot:
        image: certbot/certbot:latest
        volumes:
            - /var/certbot/conf:/etc/letsencrypt
            - /var/www/certbot:/var/www/certbot
        depends_on:
            - nginx
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
    media_volume:
    static_volume:
