version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
      - daphne

  web:
    build: ./djangobnb_backend
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn djangobnb_backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend
    env_file:
      - ./.env.dev
    depends_on:
      - db

  daphne:
    build: ./djangobnb_backend
    command: daphne -b 0.0.0.0 -p 8002 djangobnb_backend.asgi:application
    expose:
      - 8002
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=postgresdb

volumes:
  postgres_data:
